### ISSUE TITLE
偶尔发生备份报错

### ISSUE THREAD

**Issue by Lion066** [delta1037/notion-export-client#18]
使用的软件版本：notion_backup_background-v3.0.1
时间：2024-05-17
报错内容：
Unhandled exception in Script

Failed to execute script 'notion_backup_terminal' due to unhandled exception:[Errno 13]Permission denied:'C:/JGY/WebDAV/Notion/notion_backup_background-v3.backup/Projects/child_pages/产品汇报_玻璃罐封口机2024-01-10.md

Traceback (most recent call last):
  File "notion_backup_terminal.py", line 52, in <module>
  File "api\notion_dump.py", line 83, in start_dump
  File "api\notion_dump.py", line 163, in start_dump_multi
  File "api\notion_dump_api.py", line 193, in start_dump
  File "api\notion_dump_api.py", line 272, in __start_export
  File "api\notion_dump_api.py", line 641, in __relocate_child_page
  File "api\notion_dump_api.py", line 641, in __relocate_child_page
  File "api\notion_dump_api.py", line 520, in __relocate_child_page
  File "api\notion_dump_api.py", line 612, in __relocate_child_page
  File "api\notion_dump_api.py", line 323, in __relocate_link
PermissionError: [Errno 13] Permission denied: 'C:/JGY/WebDAV/Notion/notion_backup_background-v3.0.1/Notion backup/Projects/child_pages/产品汇报_玻璃罐封口机_2024-01-10.md'

**Comment by Lion066** [comment]
使用的软件版本：notion_backup_background-v3.0.1
时间：2024-06-15
报错内容：
Failed to execute script 'notion_backup_terminal' due to unhandled exception:EOF occurred in violation ofprotocol (_ssl.c:1007)

Traceback (most recent call last):
  File "httpx\_transports\default.py", line 67, in map_httpcore_exceptions
  File "httpx\_transports\default.py", line 231, in handle_request
  File "httpcore\_sync\connection_pool.py", line 216, in handle_request
  File "httpcore\_sync\connection_pool.py", line 196, in handle_request
  File "httpcore\_sync\http_proxy.py", line 317, in handle_request
  File "httpcore\_backends\sync.py", line 152, in start_tls
  File "contextlib.py", line 153, in __exit__
  File "httpcore\_exceptions.py", line 14, in map_exceptions
httpcore.ConnectError: EOF occurred in violation of protocol (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "notion_backup_terminal.py", line 52, in <module>
  File "api\notion_dump.py", line 83, in start_dump
  File "api\notion_dump.py", line 195, in start_dump_multi
  File "api\backup_info.py", line 71, in add_backup_log
  File "notion_client\api_endpoints.py", line 208, in create
  File "notion_client\client.py", line 191, in request
  File "httpx\_client.py", line 915, in send
  File "httpx\_client.py", line 943, in _send_handling_auth
  File "httpx\_client.py", line 980, in _send_handling_redirects
  File "httpx\_client.py", line 1016, in _send_single_request
  File "httpx\_transports\default.py", line 230, in handle_request
  File "contextlib.py", line 153, in __exit__
  File "httpx\_transports\default.py", line 84, in map_httpcore_exceptions
httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:1007)
