### ISSUE TITLE
运行python .\notion_backup_terminal.py报错

### ISSUE THREAD

**Issue by foreverlong** [delta1037/notion-export-client#7]
Traceback (most recent call last):
  File ".\notion_backup_terminal.py", line 9, in <module>
    from api.notion_dump import NotionBackup
  File "D:\Workspace\python\notion-export-client-main\api\notion_dump.py", line 10, in <module>
    import notion_dump
ModuleNotFoundError: No module named 'notion_dump'

**Comment by xyjigsaw** [comment]
You need to install its kernel.
```
pip install notion-dump-kernel
```
